### ISSUE TITLE
Name is offset by one month

### ISSUE THREAD

**Issue by CplShepherdFIT** [peterknezek/name-day-calendar#10]
When I use `getNameOnDate(new Date())`, it returns a name that had it's day exactly one month before.

*Also the date that is being provided is correct.

**Comment by peterknezek** [comment]
Thank you for reporting this issue. I’ve identified and fixed the problem, and the corrected version is now available in release `1.1.1`

Please update to the latest version and let us know if you encounter any further issues. Thank you for helping to improve our package!
